apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: generator-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: generator-sa-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: generator-sa
  namespace: default

---
apiVersion: v1
kind: Pod
metadata:
  name: api-msg-generator-pod
spec:
  serviceAccountName: generator-sa
  containers:
  - name: goclinet
    image: evgao/demoapp:clientgo
